The code below is outdated as _meta for models has changed greatly since 1.6
app_models = APPS_MODELS[app_name] = dict((model._meta.model_name, model) for model in app.models)
AttributeError: 'str' object has no attribute '_meta'